#!/bin/sh
# Build shim for pyflakes, a Python program that needs no build, and uses Trial to run tests
#
# Build shims are short, stupid, useable, and readable.
# They provide a uniform interface to building/testing/packaging projects,
# whether they are built with make, ant, or need no compilation at all.
# They are meant to be run by buildbot, jenkins, or developers interchangably.

do_check() {
    trial pyflakes
}

# The verbs, in their natural order
case $1 in
check) do_check ;;
steps)
    # Output the steps needed to build this app
    # Since we don't even try to package Python things,
    # pyflakes only has one step.
    echo "check"
    ;;
*)
    echo "Unknown step $1";;
esac
